name: "sfdx"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SFDX CLI
        run: npm install sfdx-cli -g
      - name: Copy the salesforce key into file
        run: echo "${{ secrets.SALESFORCE_PRIVATE_KEY }}" > server.key
      - name: Authenticate
        run: sfdx force:auth:jwt:grant --client-id=${{ secrets.DEVHUB_CLIENT_ID }} --jwt-key-file=server.key --username=${{ secrets.SALESFORCE_USERNAME }} --set-default-dev-hub
      - name: Create scratch org
        run: sfdx force:org:create -f config/project-scratch-def.json -a my-scratch
      - name: Push source
        run: sfdx project deploy start --target-org my-scratch
      - name: Run tests
        run: sfdx apex test run --target-org my-scratch --result-format human --code-coverage --detailed-coverage
      - name: Check test results
        run: ${{ contains(./tests/apex, 'Failed')
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: Apex
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Delete scratch org
        run: sfdx org:delete:scratch --target-org my-scratch --no-prompt
