name: "sfdx"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SFDX CLI
        run: npm install sfdx-cli -g
      - name: Copy the salesforce key into file
        run: echo "${{ secrets.SALESFORCE_PRIVATE_KEY }}" > server.key
      - name: Authenticate
        run: sfdx force:auth:jwt:grant --clientid=${{ secrets.DEVHUB_CLIENT_ID }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername
      - name: Create scratch org
        run: sfdx force:org:create -f config/project-scratch-def.json -a my-scratch
      - name: Push source
        run: sfdx force:source:push -u my-scratch
      - name: Run tests
        run: sfdx force:apex:test:run -u my-scratch --resultformat human
      - name: Delete scratch org
        run: sfdx force:org:delete -u my-scratch --noprompt
